# File: .readthedocs.yaml
version: 2

submodules:
  include: all

build:
  os: "ubuntu-latest"
  tools:
    python: "3.11"
  apt_packages:
    - libfftw3-dev
    - build-essential

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats: []
