# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub. They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.

name: pypi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout currect repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools twine cibuildwheel
        pip install -r conda_requirements.txt

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        CIBW_BEFORE_BUILD: "apt-get update && apt-get install -y libfftw3-dev"
      run: |
        cibuildwheel --output-dir wheelhouse
        twine upload wheelhouse/*
